import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { ThemeProvider } from "next-themes";
import Layout from "@/components/Layout";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <AuthProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className="flex-1 p-6 md:p-8 lg:p-10 bg-gradient-to-r from-[#1e1e28] to-[#282a36] rounded-lg shadow-lg">
              <SidebarTrigger />
              <div className="max-w-7xl mx-auto">{children}</div>
            </main>
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}